//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStoryProjectEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LastUserType {
            get {
                return ((string)(this["LastUserType"]));
            }
            set {
                this["LastUserType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNetBibleReference {
            get {
                return ((string)(this["LastNetBibleReference"]));
            }
            set {
                this["LastNetBibleReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastStoryWorkedOn {
            get {
                return ((string)(this["LastStoryWorkedOn"]));
            }
            set {
                this["LastStoryWorkedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMemberLogin {
            get {
                return ((string)(this["LastMemberLogin"]));
            }
            set {
                this["LastMemberLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProject {
            get {
                return ((string)(this["LastProject"]));
            }
            set {
                this["LastProject"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OneStory Editor Projects")]
        public string DefMyDocsSubfolder {
            get {
                return ((string)(this["DefMyDocsSubfolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjectPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjectPaths"]));
            }
            set {
                this["RecentProjectPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProjectPath {
            get {
                return ((string)(this["LastProjectPath"]));
            }
            set {
                this["LastProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>NET</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SwordModulesUsed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SwordModulesUsed"]));
            }
            set {
                this["SwordModulesUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NET")]
        public string LastSwordModuleUsed {
            get {
                return ((string)(this["LastSwordModuleUsed"]));
            }
            set {
                this["LastSwordModuleUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastPanoramaViewTabIndex {
            get {
                return ((int)(this["LastPanoramaViewTabIndex"]));
            }
            set {
                this["LastPanoramaViewTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgUrl"]));
            }
            set {
                this["ProjectNameToHgUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgUsername {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgUsername"]));
            }
            set {
                this["ProjectNameToHgUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInStoryLanguage {
            get {
                return ((bool)(this["LookInStoryLanguage"]));
            }
            set {
                this["LookInStoryLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInNationalBT {
            get {
                return ((bool)(this["LookInNationalBT"]));
            }
            set {
                this["LookInNationalBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInEnglishBT {
            get {
                return ((bool)(this["LookInEnglishBT"]));
            }
            set {
                this["LookInEnglishBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInConsultantNotes {
            get {
                return ((bool)(this["LookInConsultantNotes"]));
            }
            set {
                this["LookInConsultantNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInCoachNotes {
            get {
                return ((bool)(this["LookInCoachNotes"]));
            }
            set {
                this["LookInCoachNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInRetellings {
            get {
                return ((bool)(this["LookInRetellings"]));
            }
            set {
                this["LookInRetellings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInTestQs {
            get {
                return ((bool)(this["LookInTestQs"]));
            }
            set {
                this["LookInTestQs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LookInAllStories {
            get {
                return ((bool)(this["LookInAllStories"]));
            }
            set {
                this["LookInAllStories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRegEx {
            get {
                return ((bool)(this["UseRegEx"]));
            }
            set {
                this["UseRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFind {
            get {
                return ((bool)(this["EnableFind"]));
            }
            set {
                this["EnableFind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LookInExpander {
            get {
                return ((bool)(this["LookInExpander"]));
            }
            set {
                this["LookInExpander"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFindWhat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFindWhat"]));
            }
            set {
                this["RecentFindWhat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentReplaceWith {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentReplaceWith"]));
            }
            set {
                this["RecentReplaceWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgNetworkUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgNetworkUrl"]));
            }
            set {
                this["ProjectNameToHgNetworkUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BiblicalTermsPath {
            get {
                return ((string)(this["BiblicalTermsPath"]));
            }
            set {
                this["BiblicalTermsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastUseForAllStories {
            get {
                return ((bool)(this["LastUseForAllStories"]));
            }
            set {
                this["LastUseForAllStories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInTestAs {
            get {
                return ((bool)(this["LookInTestAs"]));
            }
            set {
                this["LookInTestAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point GlossingFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["GlossingFormLocation"]));
            }
            set {
                this["GlossingFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlossingFormHeight {
            get {
                return ((int)(this["GlossingFormHeight"]));
            }
            set {
                this["GlossingFormHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GlossingFormWidth {
            get {
                return ((int)(this["GlossingFormWidth"]));
            }
            set {
                this["GlossingFormWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PanoramaViewDlgHeight {
            get {
                return ((int)(this["PanoramaViewDlgHeight"]));
            }
            set {
                this["PanoramaViewDlgHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PanoramaViewDlgWidth {
            get {
                return ((int)(this["PanoramaViewDlgWidth"]));
            }
            set {
                this["PanoramaViewDlgWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point PanoramaViewDlgLocation {
            get {
                return ((global::System.Drawing.Point)(this["PanoramaViewDlgLocation"]));
            }
            set {
                this["PanoramaViewDlgLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckForProgramUpdatesAtStartup {
            get {
                return ((bool)(this["AutoCheckForProgramUpdatesAtStartup"]));
            }
            set {
                this["AutoCheckForProgramUpdatesAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveTimeoutEnabled {
            get {
                return ((bool)(this["AutoSaveTimeoutEnabled"]));
            }
            set {
                this["AutoSaveTimeoutEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoAutoSaveSilently {
            get {
                return ((bool)(this["DoAutoSaveSilently"]));
            }
            set {
                this["DoAutoSaveSilently"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHideBiblePane {
            get {
                return ((bool)(this["AutoHideBiblePane"]));
            }
            set {
                this["AutoHideBiblePane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string StateTransitionFontName {
            get {
                return ((string)(this["StateTransitionFontName"]));
            }
            set {
                this["StateTransitionFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float StateTransitionFontSize {
            get {
                return ((float)(this["StateTransitionFontSize"]));
            }
            set {
                this["StateTransitionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastPrintSettings {
            get {
                return ((long)(this["LastPrintSettings"]));
            }
            set {
                this["LastPrintSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("small")]
        public string ConNoteTableFontSize {
            get {
                return ((string)(this["ConNoteTableFontSize"]));
            }
            set {
                this["ConNoteTableFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x-small")]
        public string ConNoteButtonFontSize {
            get {
                return ((string)(this["ConNoteButtonFontSize"]));
            }
            set {
                this["ConNoteButtonFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("’”„,")]
        public string RightEdgeQuotes {
            get {
                return ((string)(this["RightEdgeQuotes"]));
            }
            set {
                this["RightEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\'")]
        public string EitherEdgeQuotes {
            get {
                return ((string)(this["EitherEdgeQuotes"]));
            }
            set {
                this["EitherEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("‘‛“‟")]
        public string LeftEdgeQuotes {
            get {
                return ((string)(this["LeftEdgeQuotes"]));
            }
            set {
                this["LeftEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToAiHgUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToAiHgUrl"]));
            }
            set {
                this["ProjectNameToAiHgUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToAiHgNetworkUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToAiHgNetworkUrl"]));
            }
            set {
                this["ProjectNameToAiHgNetworkUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point CommentaryDialogLocation {
            get {
                return ((global::System.Drawing.Point)(this["CommentaryDialogLocation"]));
            }
            set {
                this["CommentaryDialogLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CommentaryDialogWidth {
            get {
                return ((int)(this["CommentaryDialogWidth"]));
            }
            set {
                this["CommentaryDialogWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CommentaryDialogHeight {
            get {
                return ((int)(this["CommentaryDialogHeight"]));
            }
            set {
                this["CommentaryDialogHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CommentaryLastIndex {
            get {
                return ((int)(this["CommentaryLastIndex"]));
            }
            set {
                this["CommentaryLastIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color TQVernacularColor {
            get {
                return ((global::System.Drawing.Color)(this["TQVernacularColor"]));
            }
            set {
                this["TQVernacularColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color TQNationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["TQNationalBtColor"]));
            }
            set {
                this["TQNationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color TQInternationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["TQInternationalBtColor"]));
            }
            set {
                this["TQInternationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color RetellingVernacularColor {
            get {
                return ((global::System.Drawing.Color)(this["RetellingVernacularColor"]));
            }
            set {
                this["RetellingVernacularColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color RetellingNationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["RetellingNationalBtColor"]));
            }
            set {
                this["RetellingNationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 192")]
        public global::System.Drawing.Color RetellingInternationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["RetellingInternationalBtColor"]));
            }
            set {
                this["RetellingInternationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color AnswersVernacularColor {
            get {
                return ((global::System.Drawing.Color)(this["AnswersVernacularColor"]));
            }
            set {
                this["AnswersVernacularColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color AnswersNationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["AnswersNationalBtColor"]));
            }
            set {
                this["AnswersNationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 0, 0")]
        public global::System.Drawing.Color AnswersInternationalBtColor {
            get {
                return ((global::System.Drawing.Color)(this["AnswersInternationalBtColor"]));
            }
            set {
                this["AnswersInternationalBtColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 192")]
        public global::System.Drawing.Color ExegeticalHelpNoteColor {
            get {
                return ((global::System.Drawing.Color)(this["ExegeticalHelpNoteColor"]));
            }
            set {
                this["ExegeticalHelpNoteColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string LastLocalizationId {
            get {
                return ((string)(this["LastLocalizationId"]));
            }
            set {
                this["LastLocalizationId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>BIMK04</string>
  <string>DZnWNke9ScuB5IThEtS8txhiXMgy+5Ca</string>
  <string>TBI74</string>
  <string>DZnWNke9ScuB5IThEtS8txhiXMgy+5Ca</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SwordModuleToUnlockKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SwordModuleToUnlockKey"]));
            }
            set {
                this["SwordModuleToUnlockKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMapiPlus {
            get {
                return ((bool)(this["UseMapiPlus"]));
            }
            set {
                this["UseMapiPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ListSwordModuleToRtl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ListSwordModuleToRtl"]));
            }
            set {
                this["ListSwordModuleToRtl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>LanguageDepot.org [resumable sync]</string>
  <string>http://resumable.languagedepot.org</string>
  <string>LanguageDepot.org [private]</string>
  <string>http://hg-private.languagedepot.org</string>
  <string>LanguageDepot.org [legacy sync]</string>
  <string>http://hg-public.languagedepot.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AdaptItDefaultServerLabels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdaptItDefaultServerLabels"]));
            }
            set {
                this["AdaptItDefaultServerLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsingHtmlForStoryBtPane {
            get {
                return ((bool)(this["UsingHtmlForStoryBtPane"]));
            }
            set {
                this["UsingHtmlForStoryBtPane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToLastStoryWorkedOn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToLastStoryWorkedOn"]));
            }
            set {
                this["ProjectNameToLastStoryWorkedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToLastMemberLogin {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToLastMemberLogin"]));
            }
            set {
                this["ProjectNameToLastMemberLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToLastUserType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToLastUserType"]));
            }
            set {
                this["ProjectNameToLastUserType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string LnCNotesNoteFontName {
            get {
                return ((string)(this["LnCNotesNoteFontName"]));
            }
            set {
                this["LnCNotesNoteFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.25")]
        public float LnCNotesNoteFontSize {
            get {
                return ((float)(this["LnCNotesNoteFontSize"]));
            }
            set {
                this["LnCNotesNoteFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>HINDI</string>
  <string>Arial Unicode MS</string>
  <string>HINWBTC</string>
  <string>Arial Unicode MS</string>
  <string>XNR</string>
  <string>Arial Unicode MS</string>
  <string>FarsiOPV</string>
  <string>Nafees Nastaleeq</string>
  <string>BurJudson</string>
  <string>Padauk</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SwordModuleToFont {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SwordModuleToFont"]));
            }
            set {
                this["SwordModuleToFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsePreviewDialogWhenAddingConNotes {
            get {
                return ((bool)(this["UsePreviewDialogWhenAddingConNotes"]));
            }
            set {
                this["UsePreviewDialogWhenAddingConNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoadLastProject {
            get {
                return ((bool)(this["AutoLoadLastProject"]));
            }
            set {
                this["AutoLoadLastProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          SourceFont\r\n          Height\t-19\r\n          Width\t0\r\n          Escape" +
            "ment\t0\r\n          Orientation\t0\r\n          Weight\t700\r\n          Italic\t0\r\n     " +
            "     Underline\t0\r\n          StrikeOut\t0\r\n          FontEncoding\t33\r\n          Ch" +
            "arSet\t0\r\n          OutPrecision\t3\r\n          ClipPrecision\t2\r\n          Quality\t" +
            "1\r\n          PitchAndFamily\t34\r\n          FaceName\t{0}\r\n          Color\t16711680" +
            "\r\n\r\n          TargetFont\r\n          Height\t-19\r\n          Width\t0\r\n          Esc" +
            "apement\t0\r\n          Orientation\t0\r\n          Weight\t700\r\n          Italic\t0\r\n  " +
            "        Underline\t0\r\n          StrikeOut\t0\r\n          FontEncoding\t33\r\n         " +
            " CharSet\t0\r\n          OutPrecision\t3\r\n          ClipPrecision\t2\r\n          Quali" +
            "ty\t1\r\n          PitchAndFamily\t34\r\n          FaceName\t{1}\r\n          Color\t0\r\n\r\n" +
            "          NavTextFont\r\n          Height\t-15\r\n          Width\t7\r\n          Escape" +
            "ment\t0\r\n          Orientation\t0\r\n          Weight\t700\r\n          Italic\t0\r\n     " +
            "     Underline\t0\r\n          StrikeOut\t0\r\n          FontEncoding\t33\r\n          Ch" +
            "arSet\t0\r\n          OutPrecision\t1\r\n          ClipPrecision\t2\r\n          Quality\t" +
            "2\r\n          PitchAndFamily\t34\r\n          FaceName\t{2}\r\n          Color\t65280\r\n\r" +
            "\n          ProjectSettings\r\n          SourceLanguageName\t{3}\r\n          TargetLa" +
            "nguageName\t{4}\r\n          DefaultCCTablePath\r\n          LastExportPath\r\n        " +
            "  LastNewDocumentFolder\t{5}\\Adapt It Unicode Work\r\n          PunctuationPairsSou" +
            "rceSet(stores space for an empty cell)\t{6}\r\n          PunctuationPairsTargetSet(" +
            "stores space for an empty cell)\t{7}\r\n\r\n          PunctuationTwoCharacterPairsSou" +
            "rceSet(ditto)\r\n          PunctuationTwoCharacterPairsTargetSet(ditto)\r\n         " +
            " SpecialTextColor\t255\r\n          RetranslationTextColor\t32896\r\n          ColorOf" +
            "NavigationText\t65280\r\n          BackupDocumentFlag\t0\r\n          RTL_Layout\t0\r\n  " +
            "        SFMescapeChar\t\\\r\n          SFMafterNewlines\t0\r\n          SourceIsRTL\t{8}" +
            "\r\n          TargetIsRTL\t{9}\r\n\r\n          NavTextIsRTL\t0\r\n          LowerCaseSour" +
            "ceLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\n          UpperCaseSourceLanguageCha" +
            "rs\tABCDEFGHIJKLMNOPQRSTUVWXYZ\r\n          LowerCaseTargetLanguageChars\tabcdefghij" +
            "klmnopqrstuvwxyz\r\n          UpperCaseTargetLanguageChars\tABCDEFGHIJKLMNOPQRSTUVW" +
            "XYZ\r\n          LowerCaseGlossLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\n         " +
            " UpperCaseGlossLanguageChars\tABCDEFGHIJKLMNOPQRSTUVWXYZ\r\n          AutoCapitaliz" +
            "ationFlag\t0\r\n          SourceHasUpperCaseAndLowerCase\t0\r\n          FontSizeForDi" +
            "alogs(points)\t12\r\n          UseSFMarkerSet\tUsfmOnly\r\n          UseFilterMarkers\t" +
            "\\_list_base \\xdc \\lit \\_double_boxed_para \\_body_text \\bt \\ef \\x \\_normal_table " +
            "\\_footnote_caller \\_dft_para_font \\h \\_unknown_para_style \\_annotation_ref \\note" +
            " \\rem \\_annotation_text \\_peripherals_base \\_heading_base \\_hdr_ftr_interlinear " +
            "\\__normal \\xk \\ide \\_horiz_rule \\_vernacular_base \\_small_para_break \\mr \\_notes" +
            "_base \\_nav_lang_interlinear \\efm \\pro \\restore \\_footer \\xo \\_single_boxed_para" +
            " \\_src_lang_interlinear \\cl \\_unknown_char_style \\ib \\xq \\_header \\vp \\_hidden_n" +
            "ote \\_tgt_lang_interlinear \\free \\r \\_gls_lang_interlinear \\ie \\xt \\va \\cp \\h1 \\" +
            "h2 \\_table_grid \\_intro_base \\fig \\ca \\h3 \\rq\r\n          ChangeFixedSpaceToRegul" +
            "arSpace\t0\r\n          BookModeFlag\t0\r\n          BookIndexValue\t-1\r\n          Save" +
            "AsXML\t1\r\n          SilConverterName\r\n          SilConverterDirectionForward\t1\r\n " +
            "         SilConverterNormalizeOutput\t0\r\n          LegacyCopyForPhraseBox\t1\r\n    " +
            "      DoAdaptingBeforeGlossing_InVerticalEdit\t1\r\n        ")]
        public string DefaultAIProjectFile {
            get {
                return ((string)(this["DefaultAIProjectFile"]));
            }
            set {
                this["DefaultAIProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          <?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
          <!--
          Note: Using Microsoft WORD 2003 or later is not a good way to edit this xml file.
          Instead, use NotePad, WordPad or Windows Explorer.
          Please note: the order of the TU elements in this xml file might differ each time the knowledge base is saved. This is not an error. -->
          <KB docVersion=""4"" srcName=""{0}"" tgtName=""{1}"" max=""1"">
          <MAP mn=""1"">
          </MAP>
          </KB>
        ")]
        public string DefaultAIKBFile {
            get {
                return ((string)(this["DefaultAIKBFile"]));
            }
            set {
                this["DefaultAIKBFile"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ose.centralus.cloudapp.azure.com")]
        public string OseServerIpAddress {
            get {
                return ((string)(this["OseServerIpAddress"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToLastStoriesSetWorkedOn {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToLastStoriesSetWorkedOn"]));
            }
            set {
                this["ProjectNameToLastStoriesSetWorkedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSendReceiveAfterTurnChange {
            get {
                return ((bool)(this["AutoSendReceiveAfterTurnChange"]));
            }
            set {
                this["AutoSendReceiveAfterTurnChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoPopupReminderAfterTurnChange {
            get {
                return ((bool)(this["AutoPopupReminderAfterTurnChange"]));
            }
            set {
                this["AutoPopupReminderAfterTurnChange"] = value;
            }
        }
    }
}
